package main

import (
	"fmt"
	"runtime"
)

func main() {
	outputSize := 16 // 128-bit digest
	maxCores := 16

	// configurable tree-construction parameters (must match the Rust speed harness)
	leafSize = 256 * bitrate // 16 KB per leaf
	treeFanout = 8           // children per internal node

	runtime.GOMAXPROCS(maxCores)

	// speed tests
	generateSpeedReport(outputSize)
	fmt.Println("Generated speed tests!")

	// sensitivity tests
	generateSensitivityTests(outputSize)
	fmt.Println("Generated text example tests!")

	// statistical confusion and diffusion means tests
	generateConfusionDiffusionMeansTests(outputSize)
	fmt.Println("Generated confusion and diffusion means tests!")

	// confusion and diffusion spread tests
	generateConfusionDiffusionSpreadTests(outputSize)
	fmt.Println("Generated confusion and diffusion spread tests!")

	// null text distribution tests
	generateNullTextDistributionTest(outputSize)
	fmt.Println("Generated null text distribution test!")

	// sample text distribution tests
	generateSampleTextDistributionTest(outputSize)
	fmt.Println("Generated sample text distribution test!")

	// character collisions test
	generateCharacterCollisionsTest(outputSize)
	fmt.Println("Generated character collisions test!")

	// byte difference test
	generateByteDifferenceTest(outputSize)
	fmt.Println("Generated byte difference test!")

	// distribution of changed bits number test
	generateChangedBitsDistributionTest(outputSize)
	fmt.Println("Generated changed bits distribution test!")

	// graphs
	generateSensitivityGraph()
	fmt.Println("Generated sensitivity graph!")

	generateValueDistributionGraphs()
	fmt.Println("Generated value distribution graphs!")

	generateConfusionDiffusionSpreadGraph(outputSize)
	fmt.Println("Generated confusion diffusion spread graph!")

	generateConfusionDiffusionHistogramGraph()
	fmt.Println("Generated confusion diffusion histogram graph!")

	generateCharacterCollisionsGraph()
	fmt.Println("Generated character collisions graph!")

	generateChangedBitsDistributionGraph()
	fmt.Println("Generated changed bits distribution graph!")

	generateSpeedGraph()
	fmt.Println("Generated speed graph!")
}
